version: '3.8'
services:
  db-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: 
      - DB_PORT=3306
      - DB_HOST=db-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080