insert into my_store.color (label, variant_id)
values
("Titan Xanh",	1),
("Titan Đen",	1),
("Titan Tự Nhiên",1),
("Titan Trắng",	1),
("Titan Xanh",	2),
("Titan Đen",	2),
("Titan Tự Nhiên", 2),
("Titan Trắng",	2),
("Titan Xanh",	3),
("Titan Đen",	3),
("Titan Tự Nhiên", 3),
("Titan Trắng",	3),
("Xanh",	4),
("Đen",	4),
("Kem",	4),
("Xanh",	5),
("Đen",	5),
("Kem",	5),
("Xanh",	6),
("Đen",	6),
("Kem",	6),
("Đen",	7),
("Xanh",	7),
("Xám",	8),
("Xanh Dương",	8),
("Xanh Lá",	8),
("Xám",	9),
("Xanh Dương",	9),
("Xanh Lá",	9),
("Xanh",	10),
("Trắng",	10),
("Đen",	11),
("Đen",	12),
("Đen",	13),
("Đen",	14),
("Bạc",	15),
("Xám",	16),
("Bạc",	16),
("Xám",	17),
("Bạc",	17),
("Xanh",	18),
("Xám",	18),
("Xanh",	19),
("Bạc",	19),
("Hồng",	19),
("Vàng",	19),
("Xanh",	20),
("Bạc",	20),
("Hồng",	20),
("Vàng",	20),
("Xám",	21),
("Xám",	22),
("Xám",	23),
("Bạc",	23),
("Xám",	24),
("Bạc",	24),
("Trắng",	25),
("Trắng",	26),
("Đen",	27),
("Trắng",	27),
("Đen",	28),
("Hồng",	29),
("Trắng",	29),
("Đen",	29)

;